### ISSUE TITLE
Activity log broken after latest update

### ISSUE THREAD

**Issue by motiejuss** [wp-slimstat/wp-slimstat#2]
Hi

Updated Slimstat Analytics to the latest version (4.8.2) and activity log doesn't show anything anymore. 

![image](https://user-images.githubusercontent.com/888798/59032477-b1a60500-8866-11e9-9c82-642a6460b252.png)
![image](https://user-images.githubusercontent.com/888798/59032524-cb474c80-8866-11e9-93df-5a601fc90a50.png)

Other widgets like Page Views, etc. seems to be working fine.

**Comment by slimstat** [comment]
Hi, could you please contact us at https://support.wp-slimstat.com to investigate this further? Thank you.
