### ISSUE TITLE
Possible XSS attempt

### ISSUE THREAD

**Issue by sandrodz** [wp-slimstat/wp-slimstat#3]
We've discovered this in the logs:

```
admin.php?page=slimview1&fs[resource]=equals+u/K?YY_XK?_?P??[???њ[_???QK???KT_??ܘ[KX[?_Q[_Y?X?[_]_KQ?ZY_[_[??L?_?__??_OY[??_?_L??̍L?P??ь?QP?_Q?АQQ???_P?Ќ?L__M_?__
```
Seems like an XSS attempt.

**Comment by slimstat** [comment]
Hi Sandro,

it does indeed look like an XSS attempt. That input is sanitized, however I will run some tests and see if there's anything else we can add to prevent this kind of XSS attack. Notice, however, that only logged in users (that you should be able to trust more than regular anonymous users) can access that page.
