### ISSUE TITLE
Maxmind DBs already installed

### ISSUE THREAD

**Issue by reetp** [wp-slimstat/wp-slimstat#8]
I've seen this PR but can I make a request?

https://github.com/slimstat/wp-slimstat/pull/5

I already have the Maxmind libraries for use with my mail server (I have a licence)

Can there be an option to point to already installed libraries? No point in downloading them twice. Doesn't help me or Maxmind!

**Comment by robertoschwald** [comment]
Is it really worth the efforts? The DB is not that big..

**Comment by reetp** [comment]
It was just a request. Just hate seeing needless duplication!

I'd just figured it required far less code to use an existing db than doing the whole thing and wouldn't be a big issue.

**Comment by robertoschwald** [comment]
I'll take a look at it. So you do not want to get updates, either?

**Comment by reetp** [comment]
Hi, and thanks for responding!

Nope - the server does all that on a cron already. All it needs is a 'look here for DBs' type thing - no keys etc etc as that is all taken care of. I just need to make sure the install can access the DB dir via openbasedir or whatever. Simple as. I have a number of other things that access those DBs already.

Yes, I can imagine people on webhosting will need your system as they don't control crons etc.

But for those of us doing our thing it isn't required.
